using Microsoft.EntityFrameworkCore.Migrations;

namespace PieShop.Migrations
{
    public partial class SeedPies : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl) VALUES('Apple Pie', 12.95, 'Our famous apple pies!', 'Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.', 1, 'https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg', 'true', 'true', 'https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg')");
            migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl) VALUES('Blueberry Cheese Cake', '18.95', 'You''ll love it!', 'Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.', 2, 'https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecake.jpg', 'true', 'false', 'https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecakesmall.jpg')");
            migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl) VALUES('Cheese Cake', '18.95', 'Plain cheese cake. Plain pleasure.', 'Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.', 2, 'https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecake.jpg', 'true', 'false', 'https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecakesmall.jpg')");
            migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl) VALUES('Cherry Pie', '15.95', 'A summer classic!', 'Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.', 1, 'https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypie.jpg', 'true', 'false', 'https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypiesmall.jpg')");
            migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl) VALUES('Christmas Apple Pie', '13.95', 'Happy holidays with this pie!', 'Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.', 3, 'https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepie.jpg', 'true', 'false', 'https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepiesmall.jpg')");
            migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl) VALUES('Cranberry Pie', '17.95', 'A Christmas favorite', 'Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake pie chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon pie muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart pie cake danish lemon drops. Brownie cupcake dragée gummies.', 3, 'https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypie.jpg', 'true', 'false', 'https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypiesmall.jpg')");
            //migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl, AllergyInformation) VALUES('', '', '', '', '', '', '', '', '', '')");
            //migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl, AllergyInformation) VALUES('', '', '', '', '', '', '', '', '', '')");
            //migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, CategoryId, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl, AllergyInformation) VALUES('', '', '', '', '', '', '', '', '', '')"); migrationBuilder.Sql("INSERT INTO dbo.Pies(Name, Price, ShortDescription, LongDescription, Category, ImageUrl, InStock, IsPieOfTheWeek, ImageThumbnailUrl, AllergyInformation) VALUES('', '', '', '', '', '', '', '', '', '')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
